version: '3.8'
services: 
  wechatbot_test:
    image: "wechatbot"
    container_name: wechatbot_test
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:${PORT}
    env_file:
      - ./.env.test  
    volumes:
      - ./:/app/